---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: jenkins
      targetPort: 8080
      port: 8080
      nodePort: 31000